name: habit_breaker_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # State Management
  flutter_riverpod: ^2.4.9
  
  # Local Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Navigation
  go_router: ^16.1.0
  
  # UI & Screen Adaptation
  flutter_screenutil: ^5.9.0
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  
  # Network
  dio: ^5.4.0
  
  # Charts & Data Visualization
  fl_chart: ^0.63.0
  
  # Notifications & Background Tasks
  flutter_local_notifications: ^19.4.0
  workmanager: ^0.9.0+2
  timezone: ^0.10.0
  
  # Storage
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.0
  
  # Internationalization
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  
  # Utilities
  logger: ^2.0.2
  equatable: ^2.0.5
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  # Code Generation
  hive_generator: ^2.0.1
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
