name: Flutter CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.1'
        cache: true
    - name: Display Flutter version
      run: flutter --version
    - name: Display Dart version before pub get
      run: dart --version
    - name: Install dependencies with verbose output
      run: flutter pub get -v
    - name: Check pub get results
      if: failure()
      run: |
        echo "pub get failed. Printing Flutter version..."
        flutter --version
        echo "Printing Dart version..."
        dart --version
        echo "Printing .flutter directory..."
        ls -la $HOME/.flutter
        echo "Printing environment variables..."
        env
    - name: Run tests with verbose output
      run: |
        echo "Flutter version: $(flutter --version)"
        echo "Dart version: $(dart --version)"
        flutter test -v
    - name: Check test results
      if: failure()
      run: |
        echo "Test failed. Printing directory structure..."
        ls -la
        echo "Printing pubspec.yaml..."
        cat pubspec.yaml

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.1'
        cache: true
    - name: Display Flutter version
      run: flutter --version
    - name: Display Dart version before pub get in build
      run: dart --version
    - name: Install dependencies with verbose output in build
      run: flutter pub get -v
    - name: Check pub get results in build
      if: failure()
      run: |
        echo "pub get failed in build. Printing Flutter version..."
        flutter --version
        echo "Printing Dart version..."
        dart --version
        echo "Printing environment variables..."
        env
    - name: Build web with verbose output
      run: flutter build web -v
    - name: Build APK
      run: flutter build apk --release
    - name: Upload web build
      uses: actions/upload-artifact@v4
      with:
        name: web-build
        path: build/web
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: apk-build
        path: build/app/outputs/flutter-apk/app-release.apk

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: write
      actions: read
    steps:
    - name: Download APK artifact
      uses: actions/download-artifact@v4
      with:
        name: apk-build
        path: ./
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
        files: app-release.apk
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}    #  with:
    #    name: apk-build
    #    path: build/app/outputs/flutter-apk/app-release.apk